export const actions = {
    SET_EVENTS: 'SET_EVENTS',
    SET_GLOBAL_INDEXES: 'SET_GLOBAL_INDEXES',
    SET_STATUSES: 'SET_STATUSES',
    SET_EVENT_TYPES: 'SET_EVENT_TYPES',
    ADD_FILTER_EVENT_TYPES: 'ADD_FILTER_EVENT_TYPES',
    ADD_FILTER_EVENT_STATUSES: 'ADD_FILTER_EVENT_STATUSES',
    DELETE_FILTER_EVENT_TYPES: 'DELETE_FILTER_EVENT_TYPES',
    DELETE_FILTER_EVENT_STATUSES: 'DELETE_FILTER_EVENT_STATUSES',
    SET_FILTER_START_DATE: 'SET_FILTER_START_DATE',
    SET_FILTER_END_DATE: 'SET_FILTER_END_DATE',
};